name: my_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.19
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - torch=2.3.1
  - torchvision=0.18.1
  - transformers=4.32.1
  - matplotlib-inline=0.1.7
  - jupyter_client=8.6.2
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jupyter_core=5.7.2
  - requests=2.32.3
  - pyyaml=6.0.1
  - pip
